# Generated by Django 6.0 on 2026-03-31 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndiceCAC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True, verbose_name='Mes del Índice')),
                ('costo_construccion', models.DecimalField(decimal_places=2, max_digits=12)),
                ('materiales', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mano_obra', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'verbose_name': 'Índice CAC',
                'verbose_name_plural': 'Índices CAC',
                'ordering': ['-fecha'],
            },
        ),
    ]
